color0 #ffdbcf
color1 #ba1a1a
color2 #a63500
color3 #96482b
color4 #705d00
color5 #a4624b
color6 #a4624b
color7 #261814
color8 #8e7167
color9 #ba1a1a
color10 #a63500
color11 #96482b
color12 #705d00
color13 #a4624b
color14 #a4624b
color15 #261814

cursor                #261814
cursor_text_color     #fff8f6
background            #fff8f6
foreground            #261814
selection_foreground  #5a4139
selection_background  #ffdbcf
active_border_color   #a63500
inactive_border_color #ffdbcf
url_color             #a63500

active_tab_foreground   #ffffff
active_tab_background   #a63500
inactive_tab_foreground #5a4139
inactive_tab_background #ffdbcf
cursor_trail_color      #5a4139
